# Generated by Django 3.1 on 2020-08-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobhuntadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminlogin',
            old_name='username',
            new_name='email',
        ),
    ]
