# Generated by Django 3.0.8 on 2020-08-06 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimage', models.ImageField(null='empty', upload_to='employeeimage')),
                ('username', models.CharField(max_length=200, null='empty')),
                ('password', models.CharField(max_length=200, null='empty')),
                ('email', models.CharField(max_length=200, null='empty')),
                ('phoneno', models.CharField(max_length=200, null='empty')),
                ('authentication', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null='empty', upload_to='employerlogo')),
                ('companyname', models.CharField(max_length=200, null='empty')),
                ('companyemail', models.CharField(max_length=200, null='empty')),
                ('password', models.CharField(max_length=50, null='empty')),
                ('phoneno', models.CharField(max_length=200, null='empty')),
                ('country', models.CharField(max_length=200, null='empty')),
                ('state', models.CharField(max_length=200, null='empty')),
                ('since', models.CharField(max_length=200, null='empty')),
                ('teamsize', models.CharField(max_length=200, null='empty')),
                ('category', models.CharField(max_length=200, null='empty')),
                ('description', models.CharField(max_length=2000, null='empty')),
                ('website', models.CharField(max_length=200, null='empty')),
                ('authentication', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerSocialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(null='empty')),
                ('twitter', models.URLField(null='empty')),
                ('linkedin', models.URLField(null='empty')),
                ('google', models.URLField(null='empty')),
                ('employerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployerRegister')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerNewJobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=200, null='empty')),
                ('description', models.CharField(max_length=2000, null='empty')),
                ('email', models.CharField(max_length=200, null='empty')),
                ('jobtype', models.CharField(max_length=200, null='empty')),
                ('offerdsalary', models.CharField(max_length=200, null='empty')),
                ('careerlevel', models.CharField(max_length=200, null='empty')),
                ('experience', models.CharField(max_length=200, null='empty')),
                ('gender', models.CharField(max_length=200, null='empty')),
                ('industry', models.CharField(max_length=200, null='empty')),
                ('qualification', models.CharField(max_length=200, null='empty')),
                ('country', models.CharField(max_length=200, null='empty')),
                ('city', models.CharField(max_length=200, null='empty')),
                ('deadline', models.CharField(max_length=200, null='empty')),
                ('createddate', models.DateTimeField(default=datetime.datetime(2020, 8, 6, 8, 53, 50, 408193, tzinfo=utc))),
                ('requiredknowledge', models.CharField(max_length=2000, null='empty')),
                ('educationandexperience', models.CharField(max_length=2000, null='empty')),
                ('employerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployerRegister')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeWorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=200, null='empty')),
                ('company', models.CharField(max_length=200, null='empty')),
                ('startyear', models.CharField(max_length=200, null='empty')),
                ('endyear', models.CharField(max_length=200, null='empty')),
                ('jobdescription', models.CharField(max_length=500, null='empty')),
                ('present_status', models.CharField(max_length=200, null='empty')),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSocialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(null='empty')),
                ('linkedin', models.URLField(null='empty')),
                ('twitter', models.URLField(null='empty')),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfessionalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=200, null='empty')),
                ('percentage', models.PositiveIntegerField(null='empty')),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null='empty')),
                ('image', models.ImageField(null='empty', upload_to='portfolio')),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, null='empty')),
                ('age', models.CharField(max_length=200, null='empty')),
                ('education', models.CharField(max_length=200, null='empty')),
                ('country', models.CharField(max_length=200, null='empty')),
                ('city', models.CharField(max_length=200, null='empty')),
                ('gender', models.CharField(max_length=200, null='empty')),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLanguageSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200, null='empty')),
                ('percentage', models.PositiveIntegerField(null='empty')),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeJobDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, null='empty')),
                ('jobtitle', models.CharField(max_length=200, null='empty')),
                ('experience', models.CharField(max_length=200, null='empty')),
                ('currentsalary', models.CharField(max_length=200, null='empty')),
                ('jobdescription', models.CharField(max_length=1000, null='empty')),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null='empty')),
                ('course', models.CharField(max_length=200, null='empty')),
                ('institute', models.CharField(max_length=200, null='empty')),
                ('startyear', models.CharField(max_length=200, null='empty')),
                ('endyear', models.CharField(max_length=200, null='empty')),
                ('description', models.CharField(max_length=500, null='empty')),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAwards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardname', models.CharField(max_length=200, null='empty')),
                ('year', models.CharField(max_length=200, null='empty')),
                ('description', models.CharField(max_length=500, null='empty')),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null='empty')),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
                ('employeejobdetailsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeJobDetails')),
                ('employeepersonalid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeePersonalDetails')),
            ],
        ),
    ]
