# Generated by Django 3.0.8 on 2020-08-06 12:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employernewjobpost',
            name='positionnumber',
            field=models.CharField(max_length=200, null='empty'),
            preserve_default='empty',
        ),
        migrations.AlterField(
            model_name='employernewjobpost',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 12, 17, 50, 379487, tzinfo=utc)),
        ),
    ]
