# Generated by Django 3.0.7 on 2020-06-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_tb',
            name='active',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='register_tb',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='register_tb',
            name='mobileno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='register_tb',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='register_tb',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='register_tb',
            name='usertype',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='register_tb',
            name='worktype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
