# Generated by Django 3.0.8 on 2020-08-06 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20200806_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employernewjobpost',
            name='qualification',
        ),
        migrations.AlterField(
            model_name='employernewjobpost',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 12, 18, 34, 518689, tzinfo=utc)),
        ),
    ]
