# Generated by Django 3.0.7 on 2020-06-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20200616_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_tb',
            name='active',
            field=models.CharField(default='not active', max_length=100),
        ),
    ]
