# Generated by Django 3.0.8 on 2020-07-30 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_auto_20200616_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeJobDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=200, null='True')),
                ('experience', models.CharField(max_length=200, null='True')),
                ('currentsalary', models.CharField(max_length=200, null='True')),
                ('currentsalarymax', models.CharField(max_length=200, null='True')),
                ('expectedsalary', models.CharField(max_length=200, null='True')),
                ('expectedsalarymax', models.CharField(max_length=200, null='True')),
                ('jobdescription', models.CharField(max_length=1000, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimage', models.ImageField(null='True', upload_to='employeeimage')),
                ('fullname', models.CharField(max_length=200, null='True')),
                ('age', models.CharField(max_length=200, null='True')),
                ('education', models.CharField(max_length=200, null='True')),
                ('lanquages', models.CharField(max_length=200, null='True')),
                ('country', models.CharField(max_length=200, null='True')),
                ('state', models.CharField(max_length=200, null='True')),
                ('city', models.CharField(max_length=200, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null='True')),
                ('password', models.CharField(max_length=200, null='True')),
                ('email', models.CharField(max_length=200, null='True')),
                ('phoneno', models.CharField(max_length=200, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSocialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.CharField(max_length=200, null='True')),
                ('twitter', models.CharField(max_length=200, null='True')),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null='True', upload_to='employerlogo')),
                ('since', models.CharField(max_length=200, null='True')),
                ('teamsize', models.CharField(max_length=200, null='True')),
                ('category', models.CharField(max_length=200, null='True')),
                ('description', models.CharField(max_length=2000, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=200, null='True')),
                ('companyemail', models.CharField(max_length=200, null='True')),
                ('password', models.CharField(max_length=50, null='True')),
                ('phoneno', models.CharField(max_length=200, null='True')),
                ('country', models.CharField(max_length=200, null='True')),
                ('state', models.CharField(max_length=200, null='True')),
                ('city', models.CharField(max_length=200, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerSocialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=200, null='True')),
                ('twitter', models.CharField(max_length=200, null='True')),
                ('linkedin', models.CharField(max_length=200, null='True')),
                ('google', models.CharField(max_length=200, null='True')),
                ('employerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployerRegister')),
            ],
        ),
        migrations.DeleteModel(
            name='register_tb',
        ),
        migrations.AddField(
            model_name='employerdetails',
            name='employerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployerRegister'),
        ),
        migrations.AddField(
            model_name='employeepersonaldetails',
            name='employeeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister'),
        ),
        migrations.AddField(
            model_name='employeejobdetails',
            name='employeeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister'),
        ),
    ]
