# Generated by Django 3.0.8 on 2020-08-06 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_auto_20200806_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employernewjobpost',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 16, 35, 2, 507136, tzinfo=utc)),
        ),
    ]
