# Generated by Django 3.0.8 on 2020-07-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_auto_20200730_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregister',
            name='authentication',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='employerregister',
            name='authentication',
            field=models.CharField(default='', max_length=200),
        ),
    ]
