# Generated by Django 3.0.8 on 2020-08-07 03:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_auto_20200806_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employernewjobpost',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 3, 39, 2, 673039, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=200)),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployerNewJobPost')),
            ],
        ),
    ]
