# Generated by Django 3.0.8 on 2020-08-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_auto_20200731_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerdetails',
            name='category',
            field=models.CharField(default='empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='description',
            field=models.CharField(default='empty', max_length=2000),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='logo',
            field=models.ImageField(default='empty', upload_to='employerlogo'),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='since',
            field=models.CharField(default='empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='teamsize',
            field=models.CharField(default='empty', max_length=200),
        ),
    ]
