# Generated by Django 3.0.8 on 2020-08-07 04:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_auto_20200807_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 4, 32, 40, 206724, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employernewjobpost',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 4, 32, 40, 199719, tzinfo=utc)),
        ),
    ]
