# Generated by Django 3.0.8 on 2020-08-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_auto_20200801_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerregister',
            name='category',
            field=models.CharField(max_length=200, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='employerregister',
            name='description',
            field=models.CharField(max_length=2000, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='employerregister',
            name='logo',
            field=models.ImageField(null='True', upload_to='employerlogo'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='employerregister',
            name='since',
            field=models.CharField(max_length=200, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='employerregister',
            name='teamsize',
            field=models.CharField(max_length=200, null='True'),
            preserve_default='True',
        ),
        migrations.DeleteModel(
            name='EmployerDetails',
        ),
    ]
