# Generated by Django 3.0.8 on 2020-08-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0007_auto_20200801_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerregister',
            old_name='city',
            new_name='website',
        ),
    ]
