# Generated by Django 3.0.8 on 2020-08-02 05:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0008_auto_20200801_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerNewJobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('jobtype', models.CharField(max_length=200, null=True)),
                ('offerdsalary', models.CharField(max_length=200, null=True)),
                ('careerlevel', models.CharField(max_length=200, null=True)),
                ('experience', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('industry', models.CharField(max_length=200, null=True)),
                ('qualification', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('deadline', models.CharField(max_length=200, null=True)),
                ('createddate', models.DateTimeField(default=datetime.date(2020, 8, 2))),
                ('requiredknowledge', models.CharField(max_length=2000, null=True)),
                ('educationandexperience', models.CharField(max_length=2000, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('employerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployerRegister')),
            ],
        ),
    ]
