# Generated by Django 3.0.8 on 2020-08-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0009_employernewjobpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employernewjobpost',
            name='address',
        ),
    ]
