# Generated by Django 3.0.8 on 2020-08-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0010_remove_employernewjobpost_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepersonaldetails',
            name='profileimage',
        ),
        migrations.AddField(
            model_name='employeeregister',
            name='profileimage',
            field=models.ImageField(null='True', upload_to='employeeimage'),
            preserve_default='True',
        ),
    ]
