# Generated by Django 3.0.8 on 2020-08-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0011_auto_20200802_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeejobdetails',
            name='currentsalarymax',
        ),
        migrations.RemoveField(
            model_name='employeejobdetails',
            name='expectedsalary',
        ),
        migrations.RemoveField(
            model_name='employeejobdetails',
            name='expectedsalarymax',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetails',
            name='lanquages',
        ),
    ]
