# Generated by Django 3.0.8 on 2020-08-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0012_auto_20200802_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeejobdetails',
            name='currentsalary',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employeejobdetails',
            name='experience',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employeejobdetails',
            name='jobdescription',
            field=models.CharField(max_length=1000, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employeejobdetails',
            name='jobtitle',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='age',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='city',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='country',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='education',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='fullname',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='state',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employeeregister',
            name='email',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employeeregister',
            name='password',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employeeregister',
            name='phoneno',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employeeregister',
            name='profileimage',
            field=models.ImageField(null='Empty', upload_to='employeeimage'),
        ),
        migrations.AlterField(
            model_name='employeeregister',
            name='username',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employeesocialdetails',
            name='linkedin',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employeesocialdetails',
            name='twitter',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employerregister',
            name='category',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employerregister',
            name='companyemail',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employerregister',
            name='companyname',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employerregister',
            name='country',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employerregister',
            name='description',
            field=models.CharField(max_length=2000, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employerregister',
            name='logo',
            field=models.ImageField(null='Empty', upload_to='employerlogo'),
        ),
        migrations.AlterField(
            model_name='employerregister',
            name='password',
            field=models.CharField(max_length=50, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employerregister',
            name='phoneno',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employerregister',
            name='since',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employerregister',
            name='state',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employerregister',
            name='teamsize',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employerregister',
            name='website',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employersocialdetails',
            name='facebook',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employersocialdetails',
            name='google',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employersocialdetails',
            name='linkedin',
            field=models.CharField(max_length=200, null='Empty'),
        ),
        migrations.AlterField(
            model_name='employersocialdetails',
            name='twitter',
            field=models.CharField(max_length=200, null='Empty'),
        ),
    ]
