# Generated by Django 3.0.8 on 2020-08-03 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0013_auto_20200802_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesocialdetails',
            name='facebook',
            field=models.CharField(max_length=200, null='Empty'),
            preserve_default='Empty',
        ),
        migrations.AlterField(
            model_name='employernewjobpost',
            name='createddate',
            field=models.DateTimeField(default=datetime.date(2020, 8, 3)),
        ),
    ]
