# Generated by Django 3.0.8 on 2020-08-03 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0014_auto_20200803_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepersonaldetails',
            name='state',
        ),
        migrations.CreateModel(
            name='EmployeeWorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=200, null=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('fromdate', models.CharField(max_length=200, null=True)),
                ('todate', models.CharField(max_length=200, null=True)),
                ('jobdescription', models.CharField(max_length=500, null=True)),
                ('present_status', models.CharField(max_length=200, null=True)),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfessionalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=200, null=True)),
                ('percentage', models.PositiveIntegerField(null=True)),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='portfolio')),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLanguageSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200, null=True)),
                ('percentage', models.PositiveIntegerField(null=True)),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('course', models.CharField(max_length=200, null=True)),
                ('institute', models.CharField(max_length=200, null=True)),
                ('fromdate', models.CharField(max_length=200, null=True)),
                ('todate', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAwards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('fromdate', models.CharField(max_length=200, null=True)),
                ('todate', models.CharField(max_length=200, null=True)),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeRegister')),
            ],
        ),
    ]
