# Generated by Django 3.0.8 on 2020-08-08 11:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0015_auto_20200808_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofileshortlists',
            name='employeecvid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='emp.EmployeeCoverLetter'),
        ),
        migrations.AlterField(
            model_name='employeeprofileshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 11, 50, 48, 114602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employernewjobpost',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 11, 50, 48, 104596, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 11, 50, 48, 111600, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 11, 50, 48, 112601, tzinfo=utc)),
        ),
    ]
