# Generated by Django 3.0.8 on 2020-08-08 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0016_auto_20200808_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofileshortlists',
            name='employeecvid',
        ),
        migrations.AlterField(
            model_name='employeeprofileshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 11, 59, 59, 269145, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employernewjobpost',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 11, 59, 59, 259138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 11, 59, 59, 266142, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 11, 59, 59, 267143, tzinfo=utc)),
        ),
    ]
