# Generated by Django 3.1 on 2020-08-13 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0023_auto_20200813_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofileshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 10, 31, 25, 786389, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employeereview',
            name='review',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employernewjobpost',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 10, 31, 25, 775380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 10, 31, 25, 782386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 10, 31, 25, 784387, tzinfo=utc)),
        ),
    ]
