# Generated by Django 3.1 on 2020-08-18 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0024_auto_20200813_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeejobdetails',
            name='jobdescription',
        ),
        migrations.AddField(
            model_name='employeepersonaldetails',
            name='description',
            field=models.CharField(max_length=1000, null='empty'),
            preserve_default='empty',
        ),
        migrations.AlterField(
            model_name='employeeprofileshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 9, 9, 18, 192164, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employernewjobpost',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 9, 9, 18, 182157, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 9, 9, 18, 189162, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 9, 9, 18, 191164, tzinfo=utc)),
        ),
    ]
