# Generated by Django 3.1 on 2020-08-18 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0025_auto_20200818_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepersonaldetails',
            name='address',
            field=models.CharField(max_length=700, null='empty'),
            preserve_default='empty',
        ),
        migrations.AddField(
            model_name='employeepersonaldetails',
            name='state',
            field=models.CharField(max_length=200, null='empty'),
            preserve_default='empty',
        ),
        migrations.AlterField(
            model_name='employeeprofileshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 10, 38, 59, 109816, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employernewjobpost',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 10, 38, 59, 98809, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 10, 38, 59, 106814, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 10, 38, 59, 107815, tzinfo=utc)),
        ),
    ]
