# Generated by Django 3.1 on 2020-08-20 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0027_auto_20200819_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofileshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 7, 30, 59, 953115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employernewjobpost',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 7, 30, 59, 942108, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employersocialdetails',
            name='facebook',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='employersocialdetails',
            name='google',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='employersocialdetails',
            name='linkedin',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='employersocialdetails',
            name='twitter',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 7, 30, 59, 950113, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 7, 30, 59, 951114, tzinfo=utc)),
        ),
    ]
