# Generated by Django 3.1 on 2020-08-20 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0028_auto_20200820_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerregister',
            name='address',
            field=models.CharField(max_length=500, null='empty'),
            preserve_default='empty',
        ),
        migrations.AddField(
            model_name='employerregister',
            name='city',
            field=models.CharField(max_length=200, null='empty'),
            preserve_default='empty',
        ),
        migrations.AlterField(
            model_name='employeeprofileshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 7, 34, 36, 323849, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employernewjobpost',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 7, 34, 36, 312842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 7, 34, 36, 320847, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 7, 34, 36, 321848, tzinfo=utc)),
        ),
    ]
