# Generated by Django 3.1 on 2020-08-21 23:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0032_auto_20200821_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofileshortlists',
            name='acceptdate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='employeeprofileshortlists',
            name='interviewdate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='employeeprofileshortlists',
            name='lettersentdate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='employeeprofileshortlists',
            name='reject',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='acceptdate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interviewdate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='lettersentdate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='reject',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='employeeprofileshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 23, 49, 48, 290097, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employernewjobpost',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 23, 49, 48, 290097, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 23, 49, 48, 290097, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 23, 49, 48, 290097, tzinfo=utc)),
        ),
    ]
