# Generated by Django 3.1 on 2020-08-22 00:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0034_auto_20200822_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofileshortlists',
            old_name='reject',
            new_name='rejectdate',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='reject',
            new_name='rejectdate',
        ),
        migrations.AlterField(
            model_name='employeeprofileshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 0, 12, 29, 398334, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employernewjobpost',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 0, 12, 29, 382709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 0, 12, 29, 398334, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobshortlists',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 0, 12, 29, 398334, tzinfo=utc)),
        ),
    ]
