from django.urls import path
from emp import views

urlpatterns=[
path('',views.home),
path('register/',views.register_both),
path('login/',views.login_both),
path('employerhome/',views.employer_home),
path('employerlogout/',views.employer_logout),
path('employerprofile/',views.employer_profile_edit),
path('employercontact/',views.employer_contactdetails),
path('employersocialnetworks/',views.employer_socialnetworksdetails),
path('postnewjob/',views.postnew_job),
path('employeehome/',views.employee_home),
path('employeelogout/',views.employee_logout),
path('employeeprofile/',views.employee_profile_edit),
path('employeesingleprofile/',views.employee_profile),
path('employeesocialnetworks/',views.employeesocial_networks),
path('employeecontact/',views.employee_contact),
path('employeeresume/',views.employee_resume),
path('education/',views.employee_education),
path('workexperience/',views.employee_workexperience),
path('portfolio/',views.employee_portfolio),
path('professionalskill/',views.employee_professionalskill),
path('languages/',views.employee_languages),
path('awards/',views.employee_awards),
path('candidates/',views.candidates_list),
path('employeejob/',views.employee_jobsingle),
path('totalemployers/',views.total_employers),
path('alljobs/',views.employee_alljobs),
path('employersingleprofile/',views.employer_singleprofile),
path('jobapply/',views.job_apply),
path('appliedjobs/',views.applied_jobs),
path('jobshortlistapply/',views.jobshortlist_apply),
path('jobshortlist/',views.shortlisted_jobs),
path('employeeprofileshortlist/',views.employeeprofile_shortlist),
path('resumelists/',views.resume_lists),
path('interviewmessage/',views.interview_message),
path('employeeprofileview/',views.employeeprofile_view),

]
